### ISSUE TITLE
Adding multiple startup tasks causes each to be executed multiple times

### ISSUE THREAD

**Issue by Gonyoda** [andrewlock/NetEscapades.AspNetCore.StartupTasks#2]
I'm on .NET Core 2.1.502

When I add multiple startup tasks, each one executes multiple times.  The problem is that the code in AddTaskExecutingServer looking for an ImplementationType == typeof(TaskExecutingServer) doesn't work.  service.ImplementationType is null.

Instead of scanning all the services, you can use a static boolean flag to see if we've already added the server.

**Comment by andrewlock** [comment]
Good catch, and thanks for the PR! 🙂 I'll get a new version pushed out to NuGet ASAP

**Comment by andrewlock** [comment]
I've just pushed version 0.1.1 to NuGet, so should be indexed soon. Thanks again! 🙂
