### ISSUE TITLE
Multiple IServerDescriptors for .Net Core InProcess Hosting model

### ISSUE THREAD

**Issue by BBanoth** [andrewlock/NetEscapades.AspNetCore.StartupTasks#4]
Because there are multiple registrations for IServer i.e. KestrelServer and IISHttpServer, startuptasks are not executing. Please check the attachment

![Multiple IServers](https://user-images.githubusercontent.com/42469139/58205244-bbbef400-7cfb-11e9-83bb-5c044d9f3293.png)

**Comment by BBanoth** [comment]
I even tried decorating Lastly registered IServer, i.e IISHttpServer, But IISServerSetupFilter was throwing exception .

**Comment by riker09** [comment]
I think I'm facing the same issue. Any way I can help?

**Comment by andrewlock** [comment]
Hi, yeah, unfortunately the approach in this package is a bit of an issue, for exactly the reason you've seen. I'd actually suggest using the other approach I suggested [in my blog post](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-2/), using this package instead:

https://github.com/thomaslevesque/AspNetCore.AsyncInitialization/

It requires a few more changes, but ultimately it's safer..

**Comment by riker09** [comment]
Yeah, this is exactly what I did. Well, almost exactly. I used the first approach from your second part blog post. 🙂 (https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-2/#an-example-async-database-migration)

**Comment by BBanoth** [comment]
> Hi, yeah, unfortunately the approach in this package is a bit of an issue, for exactly the reason you've seen. I'd actually suggest using the other approach I suggested [in my blog post](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-2/), using this package instead:
> 
> https://github.com/thomaslevesque/AspNetCore.AsyncInitialization/
> 
> It requires a few more changes, but ultimately it's safer..

I used that repo, Thanks ..
